# Generated by Django 5.0.1 on 2024-03-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spec_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('edible', models.BooleanField(default=False)),
                ('moje_zdjecie', models.ImageField(blank=True, null=True, upload_to='sciezka/do/katalogu/zdjec')),
                ('img1', models.ImageField(default='grzybki.jpeg', null=True, upload_to='')),
                ('img2', models.ImageField(default='grzybki.jpeg', null=True, upload_to='')),
                ('img3', models.ImageField(default='grzybki.jpeg', null=True, upload_to='')),
            ],
        ),
    ]
