# Generated by Django 5.0.1 on 2024-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_rename_spec_name_mushroom_specname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "img1",
                    models.ImageField(default="przepis.jpg", null=True, upload_to=""),
                ),
                (
                    "img2",
                    models.ImageField(default="przepis.jpg", null=True, upload_to=""),
                ),
                ("category", models.TextField(null=True)),
                ("preaper_time", models.TextField(null=True)),
                ("ingredients", models.JSONField()),
                ("instructions", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
