# Generated by Django 5.0.1 on 2024-04-26 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_recipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="preaper_time",
            new_name="preptime",
        ),
    ]
