# Generated by Django 5.0.1 on 2024-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_rename_preaper_time_recipe_preptime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.JSONField(),
        ),
    ]
