# Generated by Django 5.0.1 on 2024-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_recipe_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="mushroom",
            name="characteristics",
            field=models.JSONField(null=True),
        ),
    ]
