# Generated by Django 5.0.1 on 2024-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_course_question_coursescore_answer_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="theoryitem",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="theoryitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
