# Generated by Django 5.0.1 on 2024-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_profile_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="threshold",
            field=models.IntegerField(default=80),
        ),
    ]
