# Generated by Django 5.0.1 on 2024-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_coursescore_passed"),
    ]

    operations = [
        migrations.AddField(
            model_name="mushroom",
            name="nn_id",
            field=models.IntegerField(default=-1),
        ),
    ]
