# Generated by Django 5.0.1 on 2024-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_mushroom_nn_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mushroom",
            name="characteristics",
            field=models.JSONField(default='{"cecha": "niebieski"}', null=True),
        ),
        migrations.AlterField(
            model_name="mushroom",
            name="description",
            field=models.TextField(blank=True, default="opis grzyba", null=True),
        ),
        migrations.AlterField(
            model_name="mushroom",
            name="specname",
            field=models.CharField(default="nazwa lacinska", max_length=200),
        ),
    ]
