# Generated by Django 5.0.1 on 2024-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_alter_mushroom_characteristics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mushroom",
            name="characteristics",
            field=models.JSONField(default={"cecha": "niebieski"}, null=True),
        ),
    ]
